apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: launchs-org
resources:
  - ./secret.yaml
  - ./postgresql-secret.yaml
  - ./rbac.yaml
  - ./volume.yaml
  - ./pod-backend.yaml
  - ./pod-builder.yaml
  - ./pod-controller.yaml
  - ./pod-watcher.yaml
  - ./authbase.yaml
  - ./static.yaml
  - ./strip-middleware.yaml
  - ./ingressroute.yaml
  - ./network-policy.yaml
  - ./postgresql.yaml
images:
  - name: ghcr.io/launchs-org/backend
    newName: ghcr.io/launchs-org/new-backend
    newTag: "0.1.3"
  - name: ghcr.io/launchs-org/watcher
    newName: ghcr.io/launchs-org/new-watcher
    newTag: "0.1.3"
  - name: ghcr.io/launchs-org/builder
    newName: ghcr.io/launchs-org/new-builder
    newTag: "0.1.3"
  - name: ghcr.io/launchs-org/controller
    newName: ghcr.io/launchs-org/new-controller
    newTag: "0.1.3"
  - name: ghcr.io/launchs-org/frontend
    newName: ghcr.io/launchs-org/new-frontend
    newTag: "0.1.3"
