apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchs-org-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: launchs-org-backend
  template:
    metadata:
      labels:
        app: launchs-org-backend
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: launchs-org-backend
      containers:
        - name: launchs-org-backend
          image: ghcr.io/launchs-org/backend
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: SessionSecret
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: SessionSecret
            - name: GRPC_SERVER
              value: "auth:9000"
            - name: DATABASE_TYPE
              value: "postgres"
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: DATABASE_DSN
            - name: TASK_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: TASK_DATABASE_DSN
            - name: APP_PORT
              value: "8090"
            - name: BUILDER_PORT
              value: "8091"
            - name: WATCHER_PORT
              value: "8092"
            - name: HARBOR_URL
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: HARBOR_URL
            - name: HARBOR_PROJECT
              value: "library"
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: JWT_PUBLIC_KEY
            - name: TEMPORAL_ADDRESS
              value: "temporal-frontend.launchs-org:7233"

---
apiVersion: v1
kind: Service
metadata:
  name: launchs-org-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: launchs-org-backend
  ports:
    - port: 8080
      targetPort: 8080
