apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchs-org-builder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: launchs-org-builder
  template:
    metadata:
      labels:
        app: launchs-org-builder
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: launchs-org-builder
      serviceAccountName: launchs-org-builder
      containers:
        - name: launchs-org-builder
          image: ghcr.io/launchs-org/builder
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DATABASE_TYPE
              value: "postgres"
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: DATABASE_DSN
            - name: TASK_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: TASK_DATABASE_DSN
            - name: BUILDER_PORT
              value: "8091"
            - name: HARBOR_REGISTRY
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: HARBOR_REGISTRY
            - name: HARBOR_PROJECT
              value: "library"
            - name: HARBOR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: HARBOR_USERNAME
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: launchs-org-secret
                  key: HARBOR_PASSWORD
            - name: TEMPORAL_ADDRESS
              value: "temporal-frontend.launchs-org:7233"
