apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: launchs-org-database-cluster
  namespace: launchs-org
spec:
  teamId: "launchs-org"
  volume:
    size: 5Gi
  numberOfInstances: 3
  users:
    main:
      - superuser
      - createdb
    task_user: []
    auth:
      - createdb
  databases:
    maindb: main
    taskdb: task_user
    authdb: auth
  postgresql:
    version: "17"