# 各ユーザーのパスワードを事前に作成
# フォーマット: {teamId}-{username}.{clusterName}.credentials.postgresql.acid.zalan.do
apiVersion: v1
kind: Secret
metadata:
  name: main.launchs-org-database-cluster.credentials.postgresql.acid.zalan.do
  namespace: launchs-org
type: Opaque
data:
  username: bWFpbg==
  password: Uk4yRnVRaVVCWmhxVnNhMWpBYkpFVzNaMVo4WTkyVFBiRkt1TmNHOHJlM2Q4bjgybVJwenhQc2o3bWNMbnRZR1dQZ3hlbUM0cTVhWlJCOHY2VDlHWUQ0Sk1VdkI1QkRuaTl2ZQ==  # 要変更

---
apiVersion: v1
kind: Secret
metadata:
  name: task-user.launchs-org-database-cluster.credentials.postgresql.acid.zalan.do
  namespace: launchs-org
type: Opaque
data:
  username: dGFza191c2Vy
  password: S3hKNThSY1dock1BZFlGczYzRUpqS2NXV2lNYnZuM0xMMTBZVWZEOXFqeWVuMzByd04yZjJ1eXk3NHhzWHBWQnRNaW5rb3lvQ1BnTHRFZG9SWDAyUkttdGYwcWlaenAzQTlWeA==  # 要変更

---
apiVersion: v1
kind: Secret
metadata:
  name: auth.launchs-org-database-cluster.credentials.postgresql.acid.zalan.do
  namespace: launchs-org
type: Opaque
data:
  username: YXV0aA==
  password: d3V4Z3pIRDVrV3lFUnF0bU1MRnU5SDNXS2kyaXhYdWl6Y1ZheXNKaVhDZzg0WHUwTkNLclFBTmtyM3dVRlB0RU5jaVhXaGhZTHVyTE5pRm95NFlpRUJ3aXQ1aFFrdDBiMUxydw==  # 要変更

---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: launchs-org-database-cluster
  namespace: launchs-org
spec:
  teamId: "launchs-org"
  volume:
    size: 5Gi
  numberOfInstances: 3
  users:
    main:
      - superuser
      - createdb
    task_user: []
    auth:
      - createdb
  databases:
    maindb: main
    taskdb: task_user
    authdb: auth
  postgresql:
    version: "17"